[package]
name = "bitrpc"
version = "0.4.0"
edition = "2024"
license = "MIT"
description = "A simple Rust only RPC library based on bitcode seralization, with optional Compio transport for HTTP3 and io_uring"

[dependencies]
bitcode = "0.6.9"
async-trait = "0.1"
bitrpc-macros = { path = "bitrpc-macros", version = "0.3"}

cyper = { version = "0.8", features = ["http3", "rustls"], optional = true }
http = { version = "1", optional = true }
compio-buf = { version = "0.8", optional = true }
compio-net = { version = "0.11", optional = true }
compio-quic = { version = "0.7", features = ["h3"], optional = true }
compio-runtime = { version = "0.11", optional = true }
compio-dispatcher = { version = "0.10", optional = true }
num_cpus = { version = "1", optional = true }
reqwest = { version = "0.12", default-features = false, features = ["http2", "rustls-tls"], optional = true }

[dev-dependencies]

[features]
default = []
cyper = ["dep:cyper", "dep:http"]
compio-quic = [
    "dep:compio-buf",
    "dep:compio-net",
    "dep:compio-quic",
    "dep:compio-runtime",
    "dep:http",
]
compio-server = [
    "dep:compio-buf",
    "dep:compio-net",
    "dep:compio-quic",
    "dep:compio-runtime",
    "dep:compio-dispatcher",
    "dep:num_cpus",
    "dep:http",
]
tokio = ["dep:reqwest", "dep:http"]
